graalvm/mx

- mx.py
Perform an update only if update=True and do not force a clean.
> modified GitConfig.pull behavior to match previous hg behavior. 

- mx.py
Change implements/fixes the fallback, when binary dependency cannot be found (Download error) to plain source dependency.
> Fix: Graceful fallback when binary dependency not available

- mx.py
- mx_unittest.py
Following up on #35, I removed 'projects_primary_suite()' and refactored the existing code to use 'projects(opt_limit_to_suite=True)' rather than 'projects_opt_limit_to_suites()'.
> Removed 'projects_primary_suite()' and refactoring.

- mx.py
This adds a `mx deploy-binary --platform-dependent` option, to only deploy platform dependent build artifacts. That way, we can deploy built binaries for e.g. sparc or mac without deploying the platform independent jar files more than once.
> Add option to deploy only platform dependent binary distributions.

- mx.py
> Recognize aarch64.

- mx.py
> fixes for binary imports

- README.md
README.md now includes some guidelines on how to update the version number.
> Added information about versioning

- mx.py
> use batch processing for checkstyle command

- java/com.oracle.mxtool.junit/src/com/oracle/mxtool/junit/FindClassesByAnnotatedMethods.java
- mx.py
- mx_unittest.py
> add support for running unit tests from binary suite dependencies

- mx.py
This adds support for a suite to be able to override the source URLs of its imported suites. In particular, a new suite level `urlrewrites` attribute is added. This allows regular expression URL rewriting as in this example:
```
"urlrewrites" : [
{ 
"https://git.acme.com/(.*).git" : {
"replacement" : r”https://my.company.com/foo-git-cache/\1.git",
}
},
{ 
"https://hg.acme.com/(.*)" : {
"replacement" : r”https://my.company.com/foo-hg-cache/\1",
}
}
],
```
The rules are applied in definition order. Only rewrite rules from the primary suite are used meaning a suite may have to replicate the rewrite rules of its suite dependencies.
Note that this only adds support for (source and binary) suite import URLs. A possible follow up may be to add support for rewriting other URLs such as library …
> add support for suite import URL rewriting

- mx.py
This addresses #75.
Note that an mx global option cannot be used for this as some suites want their output root before command line options have been parsed.
> added support for MX_ALT_OUTPUT_ROOT

- java/com.oracle.mxtool.junit/src/com/oracle/mxtool/junit/EagerStackTraceDecorator.java
- mx.py
- mx_unittest.py
This has been requested by @thomaswue.
> make --eager-stacktrace on by default

- java/com.oracle.mxtool.compilerserver/src/com/oracle/mxtool/compilerserver/ECJDaemon.java
> Use String[] entry point for ECJ compiler

- mx.py
> Adding packaging of project's own dists to the incremental build in IntelliJ.

- java/com.oracle.mxtool.compilerserver/src/com/oracle/mxtool/compilerserver/CompilerDaemon.java
- mx.py
@wirthi can you please test this on your machine.
> enable use of Java compiler daemon on Windows

- mx.py
Without isolating the daemon in its own process group, killing it during `mx.abort()` kills the process group of mx which is problematic when called from NetBeans.
> Java compiler daemon must be in its own process group

- java/com.oracle.mxtool.compilerserver/src/com/oracle/mxtool/compilerserver/CompilerDaemon.java
- mx.py
> make inter-thread control field volatile

- mx.py
This adds better support for long pathnames on Windows for operations in the Python `os` and `os.path` modules that otherwise don't support them ([Issue1899](https://bugs.python.org/issue18199)).
I'm not sure if intercepting the builtin `open` function is the right way to go. The alternative is to refactor all uses of this function in mx (and possibly mx extensions) to use the `_safe_path` function added by this PR.
> more robust handling of long pathnames on Windows

- mx.py
scheckimports has an option to not complain if there are uncommitted changes and sforceimports should have the same support.  It's pretty benign in scheckimports but for sforceimports git or hg will attempt to merge so it will still ask if you want to continue.  So for example:
<pre>
$ mx sforce -i
WARNING: Uncommited changes in jvmci. Attempt to update anyway? [Yn]:
merging src/share/vm/jvmci/jvmciRuntime.cpp
merging src/share/vm/jvmci/jvmciRuntime.hpp
27 files updated, 2 files merged, 1 files removed, 0 files unresolved
</pre>
@dougxc
> Allow user to contol how sforceimports handles a dirty repository

- mx.py
- mx_benchmark.py
> Add `mx_benchmark.py`.

- mx.py
Currently, spotting the error line in bigger amounts of terminal output is quite a pain.
This commit adds the new function ```log_error```, which handles such message in an improved way:
* write message to stderr instead of stdout
* print the string in red color on the terminal (at least for unix terminals now)
> Write colored log output (at least on UNIX systems)
