mx.mx/suite.py
Most recent features in Truffle are starting to use version 0.6 of the doclet. Time to upgrade.
=> Switching to most recent version of codesnippet doclet

mx.py
We used to guess scm metadata from `hg paths`, this was already not 100% reliable with hg and seems harder in git. We should just let `suite.py` explicitly define the SCM metadata.
Along with the fix to GitConfig._path this should make it possible to use `maven-deploy` on git repos.
=> Fix maven-deploy

mx.py
`maven_group_id` was returning the artifact id and the pom was using
different group & artifact ids
=> Fix groupid used during maven-deploy

mx.py
* Use `git log` instead of `git tags` since we only want the tags that are ancestors of the current commit.
* Sort versions.
* Only call to git to get the revision number of the most recent version.
* Use `minor + 1` when not exactly at the tag.
=> Fix release_version_from_tags to match expected behaviour

mx.py
Added support for "internal" attribute on distributions to prevent access from outside containing suite. With this, you should simply be able to add `"internal" = True` to a distribution in `suite.py`.
=> added support for "internal" attribute on distributions

.gitignore, mx.py
Changed the behavior of GitConfig.pull. 
Original behavior: when update=True, do a git pull which works well when the refspec is not a commit hash.
New behavior: when update=True and rev not None, delegate to GitConfig.udpate (with force=True, discard local changes). Should this behavior be different? 
Bonus, updated GitConfig.update to suppress the "detached HEAD" warning messages when not in verbose mode. 
Bumped version to 5.6.15
=> fixed git pull

.travis.yml
This removes all 2.6 compatibility testing as discussed in https://github.com/graalvm/mx/pull/11.
=> Remove Python 2.6 compatibility testing

mx.mx/suite.py, mx.py, mx_compat.py
The changes address issue #25. Suites that rely on older mx version will use Checkstyle 6.0, while newer ones will use 6.15.
=> use checkstyle version 6.15

mx_gate.py
The dependent suites are already checked by their own gates.  Thus the previous
version did some unneeded checks.  This commit now prevents checkstyle checks
on dependent suites.
=> Only call checkstyle on the primary suite in gate

mx_gate.py
Currently, `mx gate` fails unconditionally if `JDT` or `ECLIPSE_EXE` is not available even in case the tasks which need those tools are not executed. With this change the check is only done if the tools are actually needed.
=> Gate eclipse task selection fix

mx.py, mx_gate.py
In the gates, pylint and eclipseformat run on the primary suite and on all imported suites. This is not always desirable since the imported suites should be already checked in their own gates. This pull request executes pylint and eclipseformat only on the primary suite when running the gate.
=> In the gate, run pylint and eclipseformat only on the primary suite.

mx.py
git show can return non-zero exit code when revision does not exist yet. Instead of aborting, we can just say that the revision does not exist yet.
=> Make git revision checking more resilient

mx.py, mx_gate.py
Based on #42. I'm doing this on top of the other pull request to save a version bump.
This adds a special tag `always` that's always implicitly included.
For example:
`mx -v gate --dry-run --tags build`
```
Gate task times:
0:00:00.000013        Versions [always]
0:00:00.000018        JDKReleaseInfo [always]
0:00:00.000018        Clean [build,style]
0:00:00.000016        BuildJavaWithJavac [build,style]
=======
0:00:00.000420
```
It can still be explicitly excluded:
`mx -v gate --dry-run --tags always,style -x`
```
Gate task times:
0:00:00.000018        Clean [build,style]
0:00:00.000016        BuildJavaWithJavac [build,style]
=======
0:00:00.000294
```
=> Gate tagging support

mx.py
On big systems, mx dies since it spawns too many JVMs in parallel.  We now add
an option to limit the number of cpus from the command line.
Also the memory used to detect the Xlint options of javac is limited to prevent
VM crashes on parallel builds.
=> Limit number of cpus and memory

mx.py
This allows us to use the following forms:
- "urls" : ["https://hostname.organization.org/files/{path}"]
- "sourceUrls" : ["https://hostname.organization.org/files/{sourcePath}"]
in library definitions (thus saving redundancy in suite.py files)
=> Add support for library var substitution in urls

mx.py
This field can be used to specify arbitrary things that are not interpreted by
mx.  This is useful to, e.g., depend on non-mx software like, e.g., a database
label.  Since the feature added in this commit is not backward compatible
(using new suite.py files with an older mx version will have mx complain about
the unknown key 'comment') I increased the minor revision number.
=> Allow dedicated comment field in suite definition

mx.py, mx_gate.py
This makes it possible to parallelize gate checks better.
- The `style` tag will not run any build steps, and it will do all style checks that are possible without building.
- The `build` tag will do the minimal work to get a running binary (i.e. clean, javac).
- The `fullbuild` tag does an ecj build, javac build, ideinit and findbugs.
=> gate: add separate tag for style checks that require a build

mx.py
Should fix #53 (see [HTTPError](https://docs.python.org/2/library/urllib2.html#urllib2.HTTPError))
=> Check if error is an HTTPError before accesing the code attribute

mx.py
I added a command that computes the minimum heap size required to run a Java program within a certain overhead factor.
This required some changes to `run_java` (run with a timeout) and to `_waitWithTimeout` (the timeout of a subprocess should not be fatal).
=> Compute the min heap size required to a Java program.

mx.mx/suite.py, mx.py, mx_compat.py
Truffle repository requires that every element in the API has its own **@since** tag since https://github.com/graalvm/truffle/pull/86. To make sure we don't regress in this respect, we need to turn on some automatic check.
This proposal turns on printing of warnings for `mx javadoc --unified` when a **@since** tag is missing. The warnings are then interpreted by the Truffle mx customizations as errors and fail the build. Exactly what we need.
=> Enabling check that every element in the API has its @since tag

mx.py
ideinit does an fsckprojects at the end but the IDE specific routines do not and they should.
=> Individual IDE init routines should do fsckprojects

URLConnectionDownload.java, mx.py
This change-set provides improvements to the existing `mx deploy-binary` command.
- `deploy-binary` now uses the same positional arguments as `maven-deploy`.
```
repository-id         Repository ID used for binary deploy
repository-url        Repository URL used for binary deploy, if no url is
given, the repository-id is looked up in suite.py
```
- `deploy-binary` accepts `--all-suites` to perform deployment for all dependent suites (not just primary).
- `deploy-binary` accepts `--skip-existing` to prevent deploying if the suite (of a given revision) was already deployed before.
=> Add support for transitive deploy-binary

mx.py
Based on @gilles-duboscq  suggestions I rephrased the help text of the --all-suites option. The other changes make the --skip-existing option operate on distribution- (instead of suite-) granularity.
=> Fixes for deploy-binary --skip-existing and --all-suites

mx.py
The current implementation of exists for git produces worrisome output like so:
`fatal: bad object 7de96d3ba72f2d1a2a0ef39351a3db4764c74b9c`
This uses an alternate command cat-file which only produces an error code.  I tested it by winding the state of a repo back and gc'ing the commit I would need, and then running sforceimports.  It behaved as expected but without the scary output.
=> Check for existence of git commit without producing error output

mx.py, mx_compat.py
This addresses #74.
A project can explicitly specify the Checkstyle version:
```
"com.oracle.graal.graph.test" : {
...
"checkstyleVersion" : "6.15",
...
}
```
or inherit it along with the Checkstyle config from another project:
```
"com.oracle.graal.graph" : {
...
"checkstyleVersion" : "6.15",
...
},
"com.oracle.graal.graph.test" : {
...
"checkstyle" : "com.oracle.graal.graph",
...
}
```
=> make Checkstyle version configurable per project

mx.py
In mx.graal-core/mx_graal_8.py _updateGraalPropertiesFile() calls
release_version for the jvmci suite. In the binary suite usecase this
results in: AttributeError: BinarySuite instance has no attribute
'release_version'. To make jvmci usable as binary suite release_version
is provided for class BinarySuite.
See: https://github.com/graalvm/mx/issues/71
=> Provide release_version for class BinarySuite

mx.py
Unlike mercurial you can't pull specific revisions you can only fetch and check for what you wanted.  When updating we should verify that we produced the proper revision and complain.  Otherwise you just end up with other mysterious failures because you're talking about a changeset that doesn't exist.
I tested this by putting a bogus revision in my suite.py and it's better than the old fatal bad object stuff.
Another side complaint here is that abortOnError doesn't default to true in many of these routines.  Is there any reason for this?
cc/ @dougxc
=> GitConfig.update should check that the pull actually contains the requested revision

java/com.oracle.mxtool.compilerserver/.checkstyle_checks.xml, java/com.oracle.mxtool.compilerserver/src/com/oracle/mxtool/compilerserver/JavacDaemon.java, mx.mx/suite.py, mx.py
@gilles-duboscq this is the basic version of the javac daemon stuff.  I'm not entirely happy with how it integrates with mx so any feedback is appreciated.  I'm also not sure I'm missing anything about special handling of javac versions.  mx allocates a server port and hands it into the javac daemon so that we don't have port number collisions.  That's some ugly code.  It tries to cleanly shutdown the daemon process in the build but I suspect I mean want to set daemon on the process so that it will be forcibly shutdown if the main process exits.  I've got a test build running with the daemon at https://travis-ci.org/tkrodriguez/graal-core/builds/114622495.  I've only done light local testing so far.
=> Add javac daemon mode to speed up build

mx.mx/suite.py, mx.py, mx_microbench.py
Fixes #84. This change introduces the `mx microbench` command as known from graal-core.
The core functionality is implemented in `MicrobenchExecutor` which can be sub-classed by downstream projects and attached using `mx_microbench.set_microbench_executor`.
=> Add JMH and `mx microbench` command

java/com.oracle.mxtool.compilerserver/src/com/oracle/mxtool/compilerserver/CompilerDaemon.java, java/com.oracle.mxtool.compilerserver/src/com/oracle/mxtool/compilerserver/ECJDaemon.java, mx.py
This generalizes the daemon support to add ECJ.  ecj parses the command line so I had to perform some extra tricks to maintain the separators between arguments.  The ECJ build times went from 2:42 to 1:10 in travis.  Locally it saved about 40 seconds on my mac.
@gilles-duboscq @woess
=> Split out daemon logic

mx.py
Fixes bugs/missing features that make NativeTARDistribution usable for binary deployment of non-java projects.
=> Make NativeTARDistribution usable

mx.mx/suite.py, mx.py
Fixes this issue:
```
SystemExit: dependency named com.oracle.mxtool.compilerserver was not found:
project com.oracle.mxtool.compilerserver was removed as Java compliance 1.7 cannot be satisfied by configured JDKs
```
=> support project javaCompliance value that ends with "+" as a lower bound

mx.py
mx tries to forward SIGQUIT to its children but currently it signals the whole process group which appears to contain mx itself, resulting a storm of SIGQUITs instead of a single SIGQUIT.
@gilles-duboscq I think this will let us make the buildbot timeout code do a few dumps spaced over time so we can see what's happening.
=> Only forward SIGQUIT to the child Java process not the whole process group

mx.py
NetBeans does not benefit from daemon-based compilation so disable it.
=> disable Java compilation daemon when building from NetBeans

.travis.yml
The travis gate is currently not executed in `--strict-mode` which means a missing or wrong pylint is not a failure. As a side effect we also need `ecj` since this would also cause an error.
=> travis: execute gate with --strict-mode.

mx.py
I think --force-javac is the only flag it really needs to respect or are there others?
=> Compilation of compilerserver should respect --force-javac

mx.py
We do not add non-existing source folders of NativeProjects to the
.classpath files generated by eclipseinit.
This fixes #108.
=> eclipseinit skips NativeProject dependencies

.travis.yml
Since `com.oracle.mxtool.junit` currently wants java 8 we should also use it in travis.
=> travis: use oraclejdk8.

.travis.yml
`ecj-4.5.1` is no longer available from this mirror. Switching to `ecj-4.5.2` not cause any further issues.
=> Use ecj-4.5.2 for travis

mx.py
Using an exploded JDK results in:
```
$ mx --java-home=/Users/cthalinger/jvmci/build/macosx-x86_64-normal-server-release/jdk eclipseinit
File "/Users/cthalinger/jvmci/graal-core/mx.graal-core/suite.py", line 274 in definition of com.oracle.graal.api.replacements:
JDK library JVMCI_API required by com.oracle.graal.api.replacements not provided by Java 1.8.0_92-internal (1.8) from /Users/cthalinger/jvmci/build/macosx-x86_64-normal-server-release/jdk
```
This also needs a change in the graal-core suite file:
```
diff --git a/mx.graal-core/suite.py b/mx.graal-core/suite.py
index 364136c..bf5dbf6 100644
--- a/mx.graal-core/suite.py
+++ b/mx.graal-core/suite.py
@@ -21,14 +21,14 @@ suite = {
"jdklibraries" : {
"JVMCI_SERVICES" : {
-      "path" : "jre/lib/jvmci-services.jar",
-      "sourcePath" …
```
=> Support exploded JDK.

mx.mx/suite.py, mx.py, mx_jackpot.py
Hi,
This patch adds a support for Jackpot 3.0 - Jackpot 3.0 interprets custom hint files, and reports warnings as appropriate. To use it, it should suffice to do "mx jackpot", similarly to "mx findbugs".
Comments are welcome!
Thanks!
=> Adding Jackpot 3.0 support

.travis.yml
The original resource at http://ftp.halifax.rwth-aachen.de/eclipse/eclipse/downloads/drops4/R-4.5.2-201602121500/ecj-4.5.2.jar is not available anymore and travis builds fail because of that. I suggest to use https://lafo.ssw.uni-linz.ac.at/pub/sulong-deps/ecj-4.5.2.jar instead.
=> Use ecj-4.5.2.jar from eclipse archive for travis

mx.py
Otherwise using ```log_error``` on non-string objects would fail
Based on #125
=> Add explicit type conversation inside log_error

mx.py
Not all projects have 'maven' attribute, this results in error during maven-install command invocation (can be reproduced on 'sulong' project)
=> Fix maven-install

mx.py
=> Make log() "thread-safe" to avoid empty/joined lines

mx.py
Without this fix _find_metadata_dir results in endless loop on Windows where `dirname('C:\\')` returns `'C:\\'` and this is not equal to `os.sep`. The `os.path.splitdrive(d)` splits it to `C:` and `\\`. Should be harmless on non-Windows systems. See the splitdrive [documentation](https://docs.python.org/2/library/os.path.html):
> os.path.**splitdrive**(*path*)
>
> Split the pathname path into a pair `(drive, tail)` where drive is either a drive specification or the empty string. On systems which do not use drive specifications, *drive* will always be the empty string. In all cases, `drive + tail` will be the same as path.
I'm not a Python guy, but hopefully the fix is ok.
=> _find_metadata_dir: fixed on Windows

mx.py
Followup to https://github.com/graalvm/mx/pull/142
When compiling with ECJ, this still falls back on the `javah` tool. Afaik, ECJ provides no alternative yet. This means that compiling with ECJ will break when the deprecated `javah` tool is removed from the JDK.
=> Avoid using deprecated javah tool.

mx.py
Without this change IDEA tries to use classes from JDK with same names, which results in resolve errors.
=> Fix IntelliJ order entries order

java/com.oracle.mxtool.jacoco/src/com/oracle/mxtool/jacoco/JacocoReport.java, mx.py, mx_gate.py
This allows to export Jacoco reports as XML. This way, it is possible to use coverage services like coveralls or codecov which don't seem to support the `jacoco.exec` format, but its XML format.
The new code does not change the default behavior (HTML output).
Example: `mx jacocoreport --format xml ./` generates an XML in the current directory.
=> Add ability to export Jacoco reports as XML

mx.py
Replaced calls to os.path.relpath with a safe alternative, since not every path can be made relative on Windows, due to different drives.
This is based on another PR [1], where the author asked someone else to take over since they don't have time to fix the merge conflicts [2].
~I tried running `mx gate`  but that throws an unrelated error, so it doesn't look like that works on Windows yet. So be aware that this has not passed gate yet.~
[1] : https://github.com/graalvm/mx/pull/134
[2] : https://github.com/graalvm/mx/pull/134#issuecomment-436805868
=> Fix os.path.relpath throwing

mx.py
This patch fixes issues in Windows for long-path related problems.
=> Fix long paths in Windows.

mx.py, mx_commands.py, mx_unittest.py
Running `mx help <command>` throws `'MxCommand' object has no attribute 'has_documentation'`. ~This PR adds that missing function.~
This PR:
- Replaces `has_documentation` with `get_doc`, since this simplifies usage.
- Makes sure the `unittest` command passes a doc function instead of a doc string (and removed extra newlin in doc string)
- Makes sure the `get_doc` function actually returns the documentation string.
=> Add missing has_documentation to MxCommand

mx.py, mx_benchmark.py, mx_benchplot.py, mx_compat.py, mx_findbugs.py, mx_javamodules.py, mx_sigtest.py, mx_unittest.py, mx_urlrewrites.py, select_jdk.py, tag_version.py, tests/mx.mxtests/mx_mxtests.py
In a move towards supporting python 3, I have changed all print statements in the `mx` repo to the `print` function using the `__future__` import.
The print statement is not syntactically compatible with python 3, but the print function is.
See also: https://github.com/graalvm/mx/issues/168
=> Change mx to using print function, on the road to Python 3 support

.travis.yml, mx.py, mx_benchmark.py, mx_benchplot.py, mx_compat.py, mx_downstream.py, mx_gate.py, mx_javamodules.py, mx_native.py, mx_portable.py, mx_unittest.py, mx_urlrewrites.py, select_jdk.py, tag_version.py
(Remaking this as one big PR after being requested to per email)
This PR adds python 3 support to mx. It has been tested by running `mx --strict-compliance gate --strict-mode` on python 2.7.15 and python 3.6.5, both using pylint 1.9.3 (needed for 3.6). So, this PR depends on my pylint PR; https://github.com/graalvm/mx/pull/176 . This PR also definitively drops support for python 2.6 (if it was still working).
The cornerstone of this PR is the new `mx_portable` file. Because there are some modules, functions and types that are not available on both python 2 & 3, this module detects the python version and imports the right thing for that version, exposing it under a common, portable name. Then other mx modules can import that portable name from the `mx_portable` module [1].
The changes made …
=> Python 3 Support

mx.py
Correcting the error message printed when the request sent to the compiler daemon fails: compiler daemon is called javac and not java. Also adding a space to separate the command from the arguments.
On the back of [the discussions](https://github.com/oracle/graal/issues/1243#issuecomment-500603776) on the reported issue https://github.com/oracle/graal/issues/1243
See output at https://circleci.com/gh/neomatrix369/awesome-graal/423 (search for `CalledProcessError`, we now see the correct message:
```
CalledProcessError: Command '/root/project/graal-jvmci-8/openjdk1.8.0-internal/linux-amd64/product/bin/javac -g -d /root/project/graal/compiler/mxbuild/src/org.graalvm.compiler.replacements.test/bin
[snipped]
```
=> Correct error log message post compiler daemon crash

mx.py, mx_javamodules.py
This option allows us to build Graal with an exploded JDK like this:
```
mx --java-home=$(JDK_OUTPUTDIR) --jmods-dir=$(IMAGES_OUTPUTDIR)/jmods
```
This is necessary if someone wants to build a JDK image with an upstream Graal module.
=> Add --jmods-dir

mx_javamodules.py
The JDK regression test `tools/jlink/plugins/SystemModuleDescriptors/SystemModulesTest.java` fails with:
```
java.lang.NullPointerException
at SystemModulesTest.checkAttributes(SystemModulesTest.java:115)
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
at SystemModulesTest.testSystemModules(SystemModulesTest.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccesso …
```
=> Add --target-platform to jmod invocation

jdk_distribution_parser.py, mx.py, mx_commands.py, mx_fetchjdk.py
Adds `mx fetch-labsjdk` command to `mx` which downloads JDK required for project building and outputs corresponding JAVA_HOME export command to stdout. 
```
$ mx fetch-jdk --help
usage: mx fetch-labsjdk [-h] [--java-distribution JAVA_DISTRIBUTION]
[--configuration CONFIGURATION] [--to TO]
[--alias ALIAS] [--keep-archive] [-q]
...
optional arguments:
-h, --help            show this help message and exit
--java-distribution JAVA_DISTRIBUTION
JDK distribution which should be downloaded
--configuration CONFIGURATION
location of configuration json file
--to TO               location where JDK would be downloaded
--alias ALIAS         name of symlink to JDK
--keep-archive        keep downloaded JDK archive
-q, --quiet           suppress logging output
```
If command is ran without `quiet` and …
=> Add `fetch-jdk` command

mx.py
When your IDE is running on a different machine to the JVM then
the debug port needs to be given as hostname:port, or just *:port
to allow any machine to connect.
However, mx requires the dbg-port argument to be an integer.
Simply remove this requirement, allowing, for example:
mx --dbg *:8000 unittest mytest
=> Allow java debug port to use remote addresses

mx.py, mx_downstream.py, mx_gate.py, mx_ideconfig.py
When primary suite is not in a git repository look for the top most
directory containing a .mx_vcs_root file and use that directory as the
sources root.
Closes #217
=> When not in a git repository look for .mx_vcs_root file

select_jdk.py
The existing code always used . when finding suite.py
=> Ensure select_jdk.sh finds the env file when --suite-dir is used

mx.mx/suite.py, mx.py
This patch adds support for musl-based Linux distros such as Alpine. This is needed in order to enable musl-based GraalVM builds.
I've chosen rather simple approach and just introduced a new `os_arch`: `linux-musl`. It is detected by parsing `ldd` output. Because it's more costly than just examining `sys.platform`, the result is cached in a global var. This new arch type is used right away in `suite.py` to define musl-based Ninja binary.
This solution is mostly backward compatible, I don't expect it to break many existing projects. Builds may start failing when run on musl-based Linux (because the `linux-musl` key is lacking), but they would have failed anyway later when they try to execute glibc-based binaries they'd have downloaded from the `linux` section.
=> Linux-musl support

mx.py
Right now, `mx` refuses to run on M1 Macs (#232).
Allow to specify a custom architecture target. Useful for arm64-based Apple computers, until all used native libraries are released for arm64.
Example usage:
mx --arch amd64 ...
=> Add --arch global option to support arm64 macOS via Rosetta2

README.md, mx.py, mx_urlrewrites.py
Resources get told their path in the constructor argument when created, but `PackedResourceLibrary` changes that path to a path computed by `_get_path_in_cache` later in the constructor. With SHA1 override in place, subsequent calls to the `get_path` method returned a different path than the resource was constructed with, resulting in an error.
This fixes the bug in `_load_libraries`. An alternative would probably be to apply the SHA1 override in `_get_path_in_cache`. Let me know if this sounds more logical ?
=> Fixes #244 when `get_path` is used on packed resources

mx
Python 2 is being or has been phased out of default installations on many systems. [PEP 394](https://legacy.python.org/dev/peps/pep-0394/) means systems such as Ubuntu will not alias `python3` to `python` by default. In order to use the Python 3 binary with mx, the end user must either set `MX_PYTHON=python3`, `MX_PYTHON_VERSION=3`, or set up an alias by some other means. It would be helpful if mx checked if `python3` exists and use it, as part of its existing executable search.
This should maintain full backwards-compatibility. The `python3` binary is only chosen if `python2.7`, `python2`, and `python` do not exist.
=> Add detection of `python3` binary.

mx_jardistribution.py
Fix for #258:
Replaced `shutil.copy` with a `copytree/copy` combo. On Windows, the error is gone, on Linux, builds work as usual.
=> Made `_stage_file_impl` handle both files and directories

java/com.oracle.jvmtiasmagent/src/jvmtiasmgent.c, mx.mx/suite.py, mx.py
A couple of fixes related to musl-based Linux support:
* Changed the order in which OS attributes are examined: most specific variant should come first, e.g. `linux-musl`, then `linux`, then `<others>`
* Added `-Wno-error=cpp` for `linux-musl` so that it doesn't complain about nonstandard headers such as `<sys/errno.h>`
This is needed to take advantage of https://github.com/oracle/graal/pull/3141
=> Support for musl-based Linux

.github/workflows/gate.yml, mx_ide_intellij.py
This PR:
1. Fixes a bug that only the first branch in `sdk_version_regexes` can be retrieved by `match.group(1)`;
2. Support more JDK vendors to suppress warning;
3. Try to support `mx intellijinit` on windows.
@dougxc 
Before:
```
$ mx intellijinit
Parsing /Users/yyc/Library/Application Support/JetBrains/IntelliJIdea2023.2/options/jdk.table.xml for SDK definitions
Found Python SDK /Users/yyc/.local/miniforge3/bin/python with values {'name': 'Python 3.9 (base)', 'type': 'Python SDK', 'version': '3.10.9'}
WARNING:   Couldn't understand JavaSDK version specification "Eclipse Temurin version 19.0.1" for /Users/yyc/.sdkman/candidates/java/19.0.1-tem
Found Java SDK /Users/yyc/.sdkman/candidates/java/19.0.1-tem with values {'name': '19', 'type': 'JavaSDK', 'version': '19.0.1'}
WARNING: …
```
=> More improved SDK lookup.

common.json, src/mx/_impl/mx.py
To locate the root dir of a suite, mx:
* checks if the suite is contained in one or more multiple VCS, returning the one with the deepest nesting
* if no VCS is found, looks at .mx_vcs_root and ci.hocon files
We should try both approaches and return the "most nested" result (that is, the longest path, which we assume it's the closest to the suite).
=> [GR-51173] Improve computation of suite root dirs.

src/mx/_impl/mx_proftool.py
This is helpful in restricted environments, and this is the only place where `mx --version` breaks at the moment.
=> Avoid assuming there’s a PATH variable defined
